name: Renaissance
version: ${version}
description: ${description}
authors: [molenzwiebel, Komp, skreem, TeddyTheTeddy]
main: net.hungerstruck.renaissance.RenaissancePlugin

permissions:
  renaissance.admin:
    default: op
