name: Renaissance
version: ${version}
description: ${description}
authors: [molenzwiebel, Komp, skreem, TeddyTheTeddy]
main: net.hungerstruck.renaissance.RenaissancePlugin
depend: [Speak]
commands:
   debug:
       description: This should be removed.
       permission: renaissance.debug
       usage: Enter a script idiot.
